# Generated by Django 5.1.6 on 2025-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
