# Generated by Django 5.1.6 on 2025-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_inventorymodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
